# Generated by Django 5.0.6 on 2026-06-03 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cart_type', models.CharField(choices=[('cart', 'Shopping Cart'), ('wishlist', 'Wishlist')], db_index=True, default='cart', max_length=10, verbose_name='Cart Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('checkout', 'In Checkout'), ('ordered', 'Ordered'), ('abandoned', 'Abandoned'), ('converted', 'Converted from Wishlist')], db_index=True, default='active', max_length=15, verbose_name='Status')),
                ('name', models.CharField(blank=True, help_text='Optional name for wishlist', max_length=200, verbose_name='Wishlist Name')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='0-100% discount set by admin/financial', max_digits=5, verbose_name='Discount Percent')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount', max_digits=15, verbose_name='Discount Amount')),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='percent', max_length=10, verbose_name='Discount Type')),
                ('discount_note', models.TextField(blank=True, help_text='Reason for discount', verbose_name='Discount Note')),
                ('discount_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Discount Approved At')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Converted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-clean after this date', null=True, verbose_name='Expires At')),
                ('converted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_to', to='basket.cart', verbose_name='Converted From Wishlist')),
                ('discount_set_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super_admin', 'accountant']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_given', to=settings.AUTH_USER_MODEL, verbose_name='Discount Set By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the time of adding to cart', max_digits=15, verbose_name='Unit Price')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('added_from_wishlist', models.BooleanField(default=False, verbose_name='From Wishlist')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basket.cart', verbose_name='Cart')),
                ('product', models.ForeignKey(limit_choices_to={'is_active': True, 'is_market_visible': True, 'market_quantity__gt': 0, 'market_status': 'published'}, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stock.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., "Server Upgrade 1403", "Office Setup"', max_length=200, verbose_name='Wishlist Name')),
                ('description', models.TextField(blank=True, help_text='Purpose of this wishlist', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_public', models.BooleanField(default=False, help_text='Shareable with others', verbose_name='Public')),
                ('can_convert', models.BooleanField(default=True, help_text='If False, admin has blocked conversion', verbose_name='Can Convert to Cart')),
                ('conversion_count', models.PositiveIntegerField(default=0, help_text='How many times converted to cart', verbose_name='Conversion Count')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget for this wishlist (for estimation)', max_digits=15, null=True, verbose_name='Budget Limit')),
                ('target_date', models.DateField(blank=True, help_text='When user plans to buy', null=True, verbose_name='Target Purchase Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Converted At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'db_table': 'wishlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_edit', models.BooleanField(default=False, verbose_name='Can Edit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_wishlists_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Shared By')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Shared With')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='basket.wishlist')),
            ],
            options={
                'db_table': 'wishlist_shares',
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'cart_type', 'status'], name='carts_user_id_b2ac54_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status'], name='carts_status_9d207c_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='carts_created_22c862_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('cart_type', 'cart'), ('status', 'active')), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'is_active'], name='cart_items_cart_id_aa0ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['product'], name='cart_items_product_6a1de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'is_active'], name='wishlists_user_id_12df06_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['is_active', 'can_convert'], name='wishlists_is_acti_7d5118_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['created_at'], name='wishlists_created_43649f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistshare',
            unique_together={('wishlist', 'shared_with')},
        ),
    ]
