# Generated by Django 5.0.6 on 2026-06-02 13:23

import apps.accounts.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Required if registering with email",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Required if registering with mobile",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[apps.accounts.validators.validate_iranian_phone],
                        verbose_name="Mobile",
                    ),
                ),
                (
                    "registration_method",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("mobile", "Mobile")],
                        help_text="How user registered: email or mobile",
                        max_length=10,
                        null=True,
                        verbose_name="Registration Method",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether email has been verified",
                        verbose_name="Email Verified",
                    ),
                ),
                (
                    "is_mobile_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether mobile has been verified",
                        verbose_name="Mobile Verified",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("client", "Client/Customer"),
                            ("accountant", "Accountant"),
                            ("courier", "Courier/Delivery"),
                            ("stock_keeper", "Stock Keeper"),
                        ],
                        db_index=True,
                        default="client",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="Staff Status"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Last Login IP"
                    ),
                ),
                (
                    "last_login_method",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("mobile", "Mobile")],
                        max_length=10,
                        null=True,
                        verbose_name="Last Login Method",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Failed Login Attempts"
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Locked Until"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Login"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Last Activity"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="Code")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "Register"),
                            ("login", "Login"),
                            ("reset_password", "Reset Password"),
                            ("change_mobile", "Change Mobile"),
                            ("change_email", "Change Email"),
                            ("verify_profile", "Verify Profile"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "sent_via",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS")],
                        default="sms",
                        max_length=10,
                        verbose_name="Sent Via",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Used"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="Attempts"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Used At"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Code",
                "verbose_name_plural": "OTP Codes",
                "db_table": "otp_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("legal", "Legal/Company"),
                        ],
                        db_index=True,
                        default="individual",
                        max_length=10,
                        verbose_name="Profile Type",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birth Date"),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True,
                        help_text="Landline phone number",
                        max_length=15,
                        verbose_name="Telephone",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        help_text="10-digit postal code",
                        max_length=10,
                        validators=[apps.accounts.validators.validate_postal_code],
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        help_text="10-digit national code for individuals",
                        max_length=10,
                        null=True,
                        unique=True,
                        validators=[apps.accounts.validators.validate_national_code],
                        verbose_name="National Code",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Required for legal profiles",
                        max_length=200,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="11-digit national ID for companies",
                        max_length=11,
                        null=True,
                        unique=True,
                        validators=[apps.accounts.validators.validate_national_id],
                        verbose_name="National ID",
                    ),
                ),
                (
                    "economic_code",
                    models.CharField(
                        blank=True,
                        help_text="12-digit economic code for companies",
                        max_length=12,
                        null=True,
                        unique=True,
                        validators=[apps.accounts.validators.validate_economic_code],
                        verbose_name="Economic Code",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether profile has all required fields",
                        verbose_name="Profile Completed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Device Name"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Desktop, Mobile, Tablet",
                        max_length=50,
                        verbose_name="Device Type",
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Operating System"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Browser"
                    ),
                ),
                (
                    "browser_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Browser Version"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "device_token",
                    models.CharField(
                        blank=True,
                        help_text="FCM/APNS token for push notifications",
                        max_length=500,
                        verbose_name="Device Token",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_trusted",
                    models.BooleanField(default=False, verbose_name="Trusted"),
                ),
                (
                    "last_used",
                    models.DateTimeField(auto_now=True, verbose_name="Last Used"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="First Seen"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Device",
                "verbose_name_plural": "User Devices",
                "db_table": "user_devices",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current wallet balance in Rials",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Balance",
                    ),
                ),
                (
                    "blocked_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Blocked balance for pending transactions",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Blocked Balance",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("commission", "Commission"),
                            ("bonus", "Bonus"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Amount",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Balance Before",
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Balance After",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External reference (order ID, payment ID, etc.)",
                        max_length=100,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional transaction data",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "db_table": "wallet_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "mobile"], name="users_email_69b792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_role_a8f2ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_email_verified", "is_mobile_verified"],
                name="users_is_emai_a4a81a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["user", "purpose", "is_used"],
                name="otp_codes_user_id_c67bdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpcode",
            index=models.Index(
                fields=["expires_at"], name="otp_codes_expires_348c2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["profile_type"], name="profiles_profile_3cdb9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["national_code"], name="profiles_nationa_d36462_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["national_id"], name="profiles_nationa_95fd60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["economic_code"], name="profiles_economi_71c88a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_active"], name="user_device_user_id_14e9e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["ip_address"], name="user_device_ip_addr_6a6b9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["last_used"], name="user_device_last_us_5376cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userdevice",
            unique_together={("user", "device_token")},
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "is_active"], name="wallets_user_id_919dfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["balance"], name="wallets_balance_06b896_idx"),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["wallet", "transaction_type", "status"],
                name="wallet_tran_wallet__5959bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["reference_id"], name="wallet_tran_referen_1f3089_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wallettransaction",
            index=models.Index(
                fields=["created_at"], name="wallet_tran_created_33245a_idx"
            ),
        ),
    ]
