# Generated by Django 5.0.6 on 2026-06-03 06:22

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Email Verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_mobile_verified",
            field=models.BooleanField(default=False, verbose_name="Mobile Verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[apps.accounts.validators.validate_iranian_phone],
                verbose_name="Mobile",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_method",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("mobile", "Mobile")],
                max_length=10,
                null=True,
                verbose_name="Registration Method",
            ),
        ),
    ]
