# Generated by Django 5.0.6 on 2026-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_first_name_user_last_name_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login", "Login"),
                    ("reset_password", "Reset Password"),
                    ("change_mobile", "Change Mobile"),
                    ("change_email", "Change Email"),
                    ("verify_profile", "Verify Profile"),
                    ("change_contact", "Change Contact"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Purpose",
            ),
        ),
    ]
