# Generated by Django 5.0.6 on 2026-06-06 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_user_first_name_user_last_name_alter_user_email_and_more"),
        ("basket", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Range"),
                        ],
                        default="daily",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                        ],
                        default="json",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="From Date")),
                ("to_date", models.DateField(verbose_name="To Date")),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Filters used to generate report",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Report result data",
                        verbose_name="Data",
                    ),
                ),
                (
                    "total_invoices",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Invoices"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Paid",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Discount",
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total Tax",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/",
                        verbose_name="Report File",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Report",
                "verbose_name_plural": "Financial Reports",
                "db_table": "financial_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Format: INV-YYYYMMDD-XXXXXX",
                        max_length=30,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma Invoice"),
                            ("final", "Final Invoice"),
                            ("wallet_charge", "Wallet Charge"),
                            ("refund", "Refund Invoice"),
                        ],
                        db_index=True,
                        default="proforma",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Discount",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Value Added Tax",
                        max_digits=15,
                        verbose_name="Tax (VAT)",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Shipping",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Total"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Paid"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Remaining",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRR",
                        help_text="IRR, USD, EUR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wallet", "Wallet"),
                            ("card_to_card", "Card to Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_gateway", "Online Gateway"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "payment_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Payment Due Date"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Billing Name"
                    ),
                ),
                (
                    "billing_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company"
                    ),
                ),
                (
                    "billing_national_id",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="National ID"
                    ),
                ),
                (
                    "billing_economic_code",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Economic Code"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="Billing Address"),
                ),
                (
                    "billing_postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Postal Code"
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Phone"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Internal Notes")),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Customer Notes"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Proforma expiry date",
                        null=True,
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="basket.cart",
                        verbose_name="Related Cart",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="financial.invoice",
                        verbose_name="Related Invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        db_index=True,
                        help_text="TRX-YYYYMMDD-XXXXXX",
                        max_length=30,
                        unique=True,
                        verbose_name="Transaction Number",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("payment", "Payment"),
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("refund", "Refund"),
                            ("commission", "Commission"),
                            ("adjustment", "Adjustment"),
                            ("wallet_charge", "Wallet Charge"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wallet", "Wallet"),
                            ("card_to_card", "Card to Card"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online_gateway", "Online Gateway"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Bank reference or gateway tracking code",
                        max_length=100,
                        verbose_name="Reference Code",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway Response"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verified By",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="accounts.wallet",
                        verbose_name="Wallet",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="financial.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Transaction",
                "verbose_name_plural": "Financial Transactions",
                "db_table": "financial_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                (
                    "sku",
                    models.CharField(blank=True, max_length=50, verbose_name="SKU"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Unit Price"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=9,
                        help_text="VAT percentage",
                        max_digits=5,
                        verbose_name="Tax %",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="quantity * unit_price - discount",
                        max_digits=15,
                        verbose_name="Total Price",
                    ),
                ),
                (
                    "warranty_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Warranty"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="financial.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_items",
                        to="stock.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "db_table": "invoice_items",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["user", "invoice_type", "status"],
                name="invoices_user_id_501cb2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "created_at"], name="invoices_status_218b80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment_due_date"], name="invoices_payment_4a326c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["transaction_number"], name="financial_t_transac_8afb36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["user", "transaction_type", "status"],
                name="financial_t_user_id_5e17ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["transaction_date"], name="financial_t_transac_463e97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["invoice", "status"], name="financial_t_invoice_118de9_idx"
            ),
        ),
    ]
