# Generated by Django 5.0.6 on 2026-06-06 07:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., PayPing Main, Crypto BTC",
                        max_length=100,
                        verbose_name="Gateway Name",
                    ),
                ),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("payping", "PayPing"),
                            ("zarinpal", "ZarinPal"),
                            ("crypto", "Cryptocurrency"),
                            ("card_to_card", "Card to Card"),
                            ("custom", "Custom Gateway"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("test", "Test/Sandbox"), ("live", "Live/Production")],
                        db_index=True,
                        default="test",
                        max_length=10,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="Token/API Key for PayPing",
                        max_length=500,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "sandbox_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Test token for sandbox mode",
                        max_length=500,
                        verbose_name="Sandbox API Key",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        blank=True,
                        help_text="For ZarinPal or similar",
                        max_length=200,
                        verbose_name="Merchant ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="Crypto wallet address",
                        max_length=500,
                        verbose_name="Wallet Address",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        help_text="e.g., TRC20, ERC20, BEP20",
                        max_length=50,
                        verbose_name="Network",
                    ),
                ),
                (
                    "callback_url",
                    models.URLField(
                        blank=True,
                        help_text="Override default callback URL",
                        verbose_name="Callback URL",
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        help_text="Minimum payment amount in Rials",
                        max_digits=15,
                        verbose_name="Minimum Amount",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=500000000,
                        help_text="Maximum payment amount in Rials",
                        max_digits=15,
                        verbose_name="Maximum Amount",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Gateway"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher number = higher priority",
                        verbose_name="Priority",
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional gateway-specific settings",
                        verbose_name="Extra Configuration",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payment Gateway",
                "verbose_name_plural": "Payment Gateways",
                "db_table": "payment_gateways",
                "ordering": ["-priority", "-is_default", "name"],
                "indexes": [
                    models.Index(
                        fields=["gateway_type", "mode", "is_active"],
                        name="payment_gat_gateway_4d5736_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="payment_gat_is_defa_e18b19_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("redirected", "Redirected to Gateway"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gateway_code",
                    models.CharField(
                        blank=True,
                        help_text="Payment code/ID from gateway (e.g., payping code)",
                        max_length=200,
                        verbose_name="Gateway Payment Code",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        help_text="Bank reference number",
                        max_length=200,
                        verbose_name="Reference Code",
                    ),
                ),
                (
                    "gateway_request",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Request Data"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Response Data"
                    ),
                ),
                (
                    "callback_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Callback Data"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Description"
                    ),
                ),
                (
                    "payer_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Payer IP"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verified At"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_logs",
                        to="payment.paymentgateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_logs",
                        to="financial.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_logs",
                        to="financial.financialtransaction",
                        verbose_name="Transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Log",
                "verbose_name_plural": "Payment Logs",
                "db_table": "payment_logs",
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payment_log_user_id_aaf1e1_idx"
                    ),
                    models.Index(
                        fields=["gateway", "status"],
                        name="payment_log_gateway_2563b4_idx",
                    ),
                    models.Index(
                        fields=["gateway_code"], name="payment_log_gateway_99a9c5_idx"
                    ),
                    models.Index(
                        fields=["reference_code"], name="payment_log_referen_13109e_idx"
                    ),
                ],
            },
        ),
    ]
