# Generated by Django 5.0.6 on 2026-06-06 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="Market Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=550, unique=True, verbose_name="Slug"),
                ),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Short Description"
                    ),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="Full Description"),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Market Price",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Discount Price",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                ("discount_start", models.DateTimeField(blank=True, null=True)),
                ("discount_end", models.DateTimeField(blank=True, null=True)),
                (
                    "available_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Synced with stock product market_quantity",
                        verbose_name="Available Quantity",
                    ),
                ),
                (
                    "min_order_quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Min Order"),
                ),
                (
                    "max_order_quantity",
                    models.PositiveIntegerField(default=10, verbose_name="Max Order"),
                ),
                (
                    "tags",
                    models.CharField(blank=True, max_length=500, verbose_name="Tags"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views"),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sales"),
                ),
                (
                    "wishlist_count",
                    models.PositiveIntegerField(default=0, verbose_name="Wishlists"),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "rating_count",
                    models.PositiveIntegerField(default=0, verbose_name="Rating Count"),
                ),
                (
                    "avg_value_for_money",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "avg_quality",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "avg_performance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(default=False, verbose_name="Bestseller"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="Priority"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock_product",
                    models.OneToOneField(
                        limit_choices_to={"is_market_visible": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_product",
                        to="stock.product",
                        verbose_name="Stock Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Product",
                "verbose_name_plural": "Market Products",
                "db_table": "market_products",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(max_length=2000, verbose_name="Comment")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("hidden", "Hidden"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Pinned"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Edited"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="market.productcomment",
                        verbose_name="Parent Comment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="market.marketproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Comment",
                "verbose_name_plural": "Product Comments",
                "db_table": "product_comments",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("gallery", "Gallery Image"),
                        ],
                        default="gallery",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="market/gallery/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube, Aparat, or direct video URL",
                        verbose_name="Video URL",
                    ),
                ),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="market/videos/thumbnails/",
                        verbose_name="Video Thumbnail",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Title"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Text"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Main Image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="market.marketproduct",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Media",
                "verbose_name_plural": "Product Media",
                "db_table": "product_media",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value_for_money",
                    models.PositiveSmallIntegerField(
                        help_text="1-5: How worth is the price?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Value for Money",
                    ),
                ),
                (
                    "quality",
                    models.PositiveSmallIntegerField(
                        help_text="1-5: Build and material quality",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Product Quality",
                    ),
                ),
                (
                    "performance",
                    models.PositiveSmallIntegerField(
                        help_text="1-5: Speed, efficiency, reliability",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Performance",
                    ),
                ),
                (
                    "overall",
                    models.PositiveSmallIntegerField(
                        help_text="1-5: Overall satisfaction",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Overall Rating",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="User actually bought this product",
                        verbose_name="Verified Purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="market.marketproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Rating",
                "verbose_name_plural": "Product Ratings",
                "db_table": "product_ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Review Body")),
                (
                    "pros",
                    models.TextField(
                        blank=True, help_text="One per line", verbose_name="Pros"
                    ),
                ),
                (
                    "cons",
                    models.TextField(
                        blank=True, help_text="One per line", verbose_name="Cons"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("reported", "Reported"),
                        ],
                        default="published",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="Verified Purchase"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Likes"),
                ),
                (
                    "dislikes_count",
                    models.PositiveIntegerField(default=0, verbose_name="Dislikes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="market.marketproduct",
                        verbose_name="Product",
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="market.productrating",
                        verbose_name="Rating",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Review",
                "verbose_name_plural": "Product Reviews",
                "db_table": "product_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_like", models.BooleanField(default=True, verbose_name="Like")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="market.productreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "review_likes",
            },
        ),
        migrations.AddIndex(
            model_name="marketproduct",
            index=models.Index(fields=["slug"], name="market_prod_slug_31d521_idx"),
        ),
        migrations.AddIndex(
            model_name="marketproduct",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="market_prod_is_acti_6ea2f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketproduct",
            index=models.Index(
                fields=["avg_rating"], name="market_prod_avg_rat_fe0700_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketproduct",
            index=models.Index(
                fields=["market_price"], name="market_prod_market__87504c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomment",
            index=models.Index(
                fields=["product", "status"], name="product_com_product_2fcb4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomment",
            index=models.Index(
                fields=["parent"], name="product_com_parent__7e6397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["product", "is_active"], name="product_rat_product_ec4dac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(fields=["user"], name="product_rat_user_id_425d15_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("product", "user")},
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "status"], name="product_rev_product_994e65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["user"], name="product_rev_user_id_f1d802_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewlike",
            unique_together={("review", "user")},
        ),
    ]
