# Generated by Django 5.0.6 on 2026-06-07 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "courier_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("alopeyk", "Alopeyk"),
                            ("snappbox", "SnappBox"),
                            ("post", "Post Office"),
                            ("tipax", "Tipax"),
                        ],
                        db_index=True,
                        default="internal",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("pickup", "Pickup Truck"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                        ],
                        default="motorcycle",
                        max_length=20,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Vehicle Plate"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="National Code"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Key"
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="API Secret"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="Webhook URL"),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Extra Config"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "courier"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier",
                "verbose_name_plural": "Couriers",
                "db_table": "couriers",
                "ordering": ["-is_available", "-rating"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "origin_address",
                    models.TextField(blank=True, verbose_name="Origin Address"),
                ),
                (
                    "origin_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "origin_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "destination_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "courier_tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Courier Tracking Code"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned to Courier"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "courier_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What we pay to courier",
                        max_digits=15,
                        verbose_name="Courier Cost",
                    ),
                ),
                (
                    "customer_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="What customer pays",
                        max_digits=15,
                        verbose_name="Customer Cost",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Distance (km)",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Estimated Duration (min)"
                    ),
                ),
                (
                    "package_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "package_description",
                    models.TextField(blank=True, verbose_name="Package Description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "courier_notes",
                    models.TextField(blank=True, verbose_name="Courier Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="logistics.courier",
                        verbose_name="Courier",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="financial.invoice",
                        verbose_name="Invoice",
                    ),
                ),
                (
                    "origin_warehouse",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_shipments",
                        to="stock.warehouse",
                        verbose_name="Origin Warehouse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "db_table": "shipments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned to Courier"),
                            ("picked_up", "Picked Up"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "location_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "location_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracking Event",
                "verbose_name_plural": "Tracking Events",
                "db_table": "shipment_tracking",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="home",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Home, Office, Parent's House",
                        max_length=100,
                        verbose_name="Address Title",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=150, verbose_name="Recipient Name"),
                ),
                (
                    "recipient_mobile",
                    models.CharField(max_length=11, verbose_name="Recipient Mobile"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Iran", max_length=50, verbose_name="Country"
                    ),
                ),
                ("province", models.CharField(max_length=100, verbose_name="Province")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Postal Code"
                    ),
                ),
                (
                    "address_line",
                    models.TextField(
                        help_text="Full street address", verbose_name="Address"
                    ),
                ),
                (
                    "plaque",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Plaque"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Unit"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Floor"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="From Google Maps",
                        max_digits=10,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="From Google Maps",
                        max_digits=10,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "google_place_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Google Place ID"
                    ),
                ),
                (
                    "google_formatted_address",
                    models.TextField(
                        blank=True, verbose_name="Google Formatted Address"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Default"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Verified by courier",
                        verbose_name="Verified",
                    ),
                ),
                (
                    "delivery_instructions",
                    models.TextField(
                        blank=True,
                        help_text="e.g., Ring buzzer #3, Leave at door",
                        verbose_name="Delivery Instructions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
                "db_table": "user_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="logistics.useraddress",
                verbose_name="Destination Address",
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(
                fields=["user", "is_active"], name="user_addres_user_id_d90e90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=models.Index(
                fields=["latitude", "longitude"], name="user_addres_latitud_8bdec7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipments_status_cda325_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["courier", "status"], name="shipments_courier_725a0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "status"], name="shipments_user_id_bd4912_idx"
            ),
        ),
    ]
