import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from apps.accounts.models import User
from apps.financial.enums import ReportType, ReportFormat


class FinancialReport(models.Model):
    """
    گزارش‌های مالی
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    # ==================== Report Info ====================
    title = models.CharField(
        _('Title'),
        max_length=200
    )

    report_type = models.CharField(
        _('Type'),
        max_length=15,
        choices=ReportType.choices,
        default=ReportType.DAILY
    )

    format = models.CharField(
        _('Format'),
        max_length=10,
        choices=ReportFormat.choices,
        default=ReportFormat.JSON
    )

    # ==================== Date Range ====================
    from_date = models.DateField(_('From Date'))
    to_date = models.DateField(_('To Date'))

    # ==================== Generated By ====================
    generated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='generated_reports'
    )

    # ==================== Report Data ====================
    parameters = models.JSONField(
        _('Parameters'),
        default=dict,
        help_text=_('Filters used to generate report')
    )

    data = models.JSONField(
        _('Data'),
        default=dict,
        help_text=_('Report result data')
    )

    # ==================== Summary ====================
    total_invoices = models.PositiveIntegerField(_('Total Invoices'), default=0)
    total_amount = models.DecimalField(_('Total Amount'), max_digits=15, decimal_places=2, default=0)
    total_paid = models.DecimalField(_('Total Paid'), max_digits=15, decimal_places=2, default=0)
    total_discount = models.DecimalField(_('Total Discount'), max_digits=15, decimal_places=2, default=0)
    total_tax = models.DecimalField(_('Total Tax'), max_digits=15, decimal_places=2, default=0)

    # ==================== File ====================
    report_file = models.FileField(
        _('Report File'),
        upload_to='reports/%Y/%m/',
        null=True,
        blank=True
    )

    notes = models.TextField(_('Notes'), blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'financial_reports'
        verbose_name = _('Financial Report')
        verbose_name_plural = _('Financial Reports')
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} ({self.from_date} - {self.to_date})"