# Generated by Django 5.0.6 on 2026-06-03 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Brand Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                (
                    "persian_name",
                    models.CharField(
                        blank=True,
                        help_text="نام فارسی برند",
                        max_length=200,
                        verbose_name="Persian Name",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Website")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country of Origin"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "warranty_info",
                    models.TextField(
                        blank=True,
                        help_text="General warranty policy for this brand",
                        verbose_name="Warranty Information",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Are we an official partner/reseller?",
                        verbose_name="Official Partner",
                    ),
                ),
                (
                    "popularity_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Based on sales and views",
                        verbose_name="Popularity Score",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "db_table": "brands",
                "ordering": ["-popularity_score", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_partner"],
                        name="brands_is_acti_88b088_idx",
                    ),
                    models.Index(fields=["slug"], name="brands_slug_6a4b1c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Series Name"
                    ),
                ),
                ("slug", models.SlugField(max_length=250, verbose_name="Slug")),
                (
                    "year_released",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Year Released"
                    ),
                ),
                (
                    "generation",
                    models.CharField(
                        blank=True,
                        help_text="e.g., G10, G11, Gen 2",
                        max_length=50,
                        verbose_name="Generation",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="series",
                        to="stock.brand",
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Series",
                "verbose_name_plural": "Brand Series",
                "db_table": "brand_series",
                "ordering": ["brand__name", "-year_released", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit - unique product code",
                        max_length=50,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="Product Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=350, unique=True, verbose_name="Slug"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New - Brand New"),
                            ("like_new", "Like New - Open Box"),
                            ("used", "Used - Second Hand"),
                            ("refurbished", "Refurbished"),
                            ("damaged", "Damaged - For Parts"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer model number",
                        max_length=200,
                        verbose_name="Model Number",
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer part number",
                        max_length=200,
                        verbose_name="Part Number",
                    ),
                ),
                (
                    "processor",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Intel Xeon Gold 6248R",
                        max_length=200,
                        verbose_name="Processor",
                    ),
                ),
                (
                    "processor_cores",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Cores"
                    ),
                ),
                (
                    "processor_threads",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Threads"
                    ),
                ),
                (
                    "processor_speed",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 3.0 GHz",
                        max_length=50,
                        verbose_name="Base Speed",
                    ),
                ),
                (
                    "processor_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Number of physical CPUs",
                        verbose_name="Processor Count",
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 64GB DDR4 ECC",
                        max_length=100,
                        verbose_name="RAM",
                    ),
                ),
                (
                    "ram_slots_total",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Total RAM Slots"
                    ),
                ),
                (
                    "ram_slots_used",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Used RAM Slots"
                    ),
                ),
                (
                    "ram_max",
                    models.CharField(blank=True, max_length=50, verbose_name="Max RAM"),
                ),
                (
                    "storage",
                    models.TextField(
                        blank=True,
                        help_text="Storage configuration details",
                        verbose_name="Storage",
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., SSD, HDD, NVMe",
                        max_length=100,
                        verbose_name="Storage Type",
                    ),
                ),
                (
                    "total_storage",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 2TB SSD + 4TB HDD",
                        max_length=50,
                        verbose_name="Total Storage",
                    ),
                ),
                (
                    "network",
                    models.TextField(
                        blank=True,
                        help_text="Network interfaces",
                        verbose_name="Network",
                    ),
                ),
                (
                    "network_ports",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Network Ports"
                    ),
                ),
                (
                    "gpu",
                    models.CharField(blank=True, max_length=200, verbose_name="GPU"),
                ),
                (
                    "gpu_memory",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="GPU Memory"
                    ),
                ),
                (
                    "power_supply",
                    models.CharField(
                        blank=True,
                        help_text="PSU specs",
                        max_length=200,
                        verbose_name="Power Supply",
                    ),
                ),
                (
                    "power_consumption",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 750W",
                        max_length=50,
                        verbose_name="Power Consumption",
                    ),
                ),
                (
                    "form_factor",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 1U, 2U, Tower, Mini",
                        max_length=50,
                        verbose_name="Form Factor",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="W x D x H in mm",
                        max_length=100,
                        verbose_name="Dimensions",
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="in kg",
                        max_length=50,
                        verbose_name="Weight",
                    ),
                ),
                (
                    "ports",
                    models.TextField(blank=True, verbose_name="Ports & Interfaces"),
                ),
                (
                    "additional_specs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Any other technical details",
                        verbose_name="Additional Specifications",
                    ),
                ),
                (
                    "warranty",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 3 Years Manufacturer Warranty",
                        max_length=200,
                        verbose_name="Warranty",
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Warranty Expiry"
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/images/%Y/%m/",
                        verbose_name="Main Image",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Purchase cost for inventory",
                        max_digits=15,
                        verbose_name="Cost Price",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Base selling price",
                        max_digits=15,
                        verbose_name="Selling Price",
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price shown in marketplace (can be different)",
                        max_digits=15,
                        null=True,
                        verbose_name="Market Price",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Discount %",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRR",
                        help_text="IRR, USD, EUR",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "market_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("sold_out", "Sold Out"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Market Status",
                    ),
                ),
                (
                    "market_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of units available in marketplace",
                        verbose_name="Market Quantity",
                    ),
                ),
                (
                    "is_market_visible",
                    models.BooleanField(
                        default=False,
                        help_text="Show this product in online marketplace",
                        verbose_name="Visible in Market",
                    ),
                ),
                (
                    "market_description",
                    models.TextField(
                        blank=True,
                        help_text="Description for marketplace listing",
                        verbose_name="Market Description",
                    ),
                ),
                (
                    "market_tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags for search",
                        max_length=500,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "min_stock_alert",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Alert when stock falls below this number",
                        verbose_name="Min Stock Alert",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="stock.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="stock.brandseries",
                        verbose_name="Series",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total quantity in this warehouse",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantity reserved for orders",
                        verbose_name="Reserved Quantity",
                    ),
                ),
                (
                    "minimum_quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Alert when below this level",
                        verbose_name="Minimum Quantity",
                    ),
                ),
                (
                    "shelf",
                    models.CharField(
                        blank=True,
                        help_text="Shelf or rack number",
                        max_length=50,
                        verbose_name="Shelf/Rack",
                    ),
                ),
                (
                    "aisle",
                    models.CharField(blank=True, max_length=50, verbose_name="Aisle"),
                ),
                (
                    "section",
                    models.CharField(blank=True, max_length=50, verbose_name="Section"),
                ),
                (
                    "location_barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Location Barcode",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("in_transit", "In Transit"),
                            ("damaged", "Damaged"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Batch Number"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Received Date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="For items with shelf life",
                        null=True,
                        verbose_name="Expiry Date",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Stock Check"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="stock.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "db_table": "inventory_items",
                "ordering": ["warehouse", "product__sku"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Category Name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("condition", "Condition"),
                            ("usage", "Usage"),
                            ("brand", "Brand"),
                            ("type", "Type"),
                            ("series", "Series & Year"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Category Type",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New - Brand New"),
                            ("like_new", "Like New - Open Box"),
                            ("used", "Used - Second Hand"),
                            ("refurbished", "Refurbished"),
                            ("damaged", "Damaged - For Parts"),
                        ],
                        help_text="Only for top-level categories",
                        max_length=20,
                        null=True,
                        verbose_name="Condition",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Featured"),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Category depth: 0=root, 1=condition, 2=usage, 3=brand, 4=type, 5=series",
                        verbose_name="Level",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="stock.productcategory",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "db_table": "product_categories",
                "ordering": ["level", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Lowest level category (series)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="stock.productcategory",
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="brandseries",
            name="category",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category_type": "series"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="series",
                to="stock.productcategory",
                verbose_name="Product Category",
            ),
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        upload_to="products/documents/%Y/%m/", verbose_name="File"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("datasheet", "Datasheet"),
                            ("manual", "Manual"),
                            ("warranty", "Warranty Card"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Document Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="stock.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_documents",
                "ordering": ["doc_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/images/%Y/%m/", verbose_name="Image"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Title"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Main Image"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Sort Order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="stock.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Warehouse Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code: WH-MAIN-001",
                        max_length=20,
                        unique=True,
                        verbose_name="Warehouse Code",
                    ),
                ),
                (
                    "warehouse_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Warehouse"),
                            ("sub", "Sub Warehouse"),
                            ("specialized", "Specialized Warehouse"),
                            ("temporary", "Temporary Warehouse"),
                        ],
                        db_index=True,
                        default="main",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("general", "General - All Hardware"),
                            ("specialized", "Specialized - Specific Hardware"),
                        ],
                        default="general",
                        help_text="General or Specialized hardware",
                        max_length=20,
                        verbose_name="Scope",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS Latitude",
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS Longitude",
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=15, verbose_name="Phone"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum number of items",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "current_items",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current number of items",
                        verbose_name="Current Items",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Active"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Visible to customers",
                        verbose_name="Public",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "specialized_hardware",
                    models.CharField(
                        blank=True,
                        help_text="If scope is specialized, specify hardware type",
                        max_length=200,
                        verbose_name="Specialized Hardware",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["super_admin", "stock_keeper"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Warehouse Manager",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for main warehouse",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_warehouses",
                        to="stock.warehouse",
                        verbose_name="Parent Warehouse",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role__in": ["stock_keeper", "accountant"]},
                        related_name="warehouses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Warehouse Staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
                "db_table": "warehouses",
                "ordering": ["warehouse_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("transfer", "Transfer"),
                            ("reserve", "Reserved"),
                            ("unreserve", "Unreserved"),
                            ("adjustment", "Adjustment"),
                            ("return", "Return"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=30,
                        verbose_name="Movement Type",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Order number, transfer ID, etc.",
                        max_length=200,
                        verbose_name="Reference",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="stock.inventoryitem",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_movements",
                        to="stock.warehouse",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_movements",
                        to="stock.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="stock.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["category_type", "is_active"],
                name="product_cat_categor_7100d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(
                fields=["parent", "is_active"], name="product_cat_parent__85b6f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcategory",
            index=models.Index(fields=["slug"], name="product_cat_slug_801f9e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productcategory",
            unique_together={("slug", "parent")},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="products_sku_fe2039_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["condition", "is_active"], name="products_conditi_c9f127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["market_status", "is_market_visible"],
                name="products_market__2a80a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "series"], name="products_brand_i_c9bdc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
        migrations.AddIndex(
            model_name="brandseries",
            index=models.Index(
                fields=["brand", "is_active"], name="brand_serie_brand_i_691d60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brandseries",
            unique_together={("brand", "slug")},
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(
                fields=["warehouse_type", "is_active"],
                name="warehouses_warehou_1dc191_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["code"], name="warehouses_code_339055_idx"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["parent"], name="warehouses_parent__221af3_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["inventory_item", "created_at"],
                name="stock_movem_invento_74b0be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type"], name="stock_movem_movemen_d922c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["warehouse", "status"], name="inventory_i_warehou_064d5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["product", "status"], name="inventory_i_product_bb20ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["quantity"], name="inventory_i_quantit_2c9a94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("warehouse", "product", "batch_number")},
        ),
    ]
