"""A broad, curated set of hardware vendors for development data."""


def brand(name, slug, persian_name, country, score=50, website=""):
    return {
        "name": name,
        "slug": slug,
        "persian_name": persian_name,
        "country": country,
        "popularity_score": score,
        "website": website,
    }


BRANDS = (
    # Semiconductors, processors and complete systems
    brand("Intel", "intel", "اینتل", "United States", 100, "https://www.intel.com/"),
    brand("AMD", "amd", "ای‌ام‌دی", "United States", 100, "https://www.amd.com/"),
    brand(
        "NVIDIA", "nvidia", "انویدیا", "United States", 100, "https://www.nvidia.com/"
    ),
    brand("Apple", "apple", "اپل", "United States", 98, "https://www.apple.com/"),
    brand(
        "Qualcomm",
        "qualcomm",
        "کوالکام",
        "United States",
        75,
        "https://www.qualcomm.com/",
    ),
    brand(
        "Microsoft",
        "microsoft",
        "مایکروسافت",
        "United States",
        80,
        "https://www.microsoft.com/",
    ),
    brand("Dell", "dell", "دل", "United States", 95, "https://www.dell.com/"),
    brand(
        "Dell EMC",
        "dell-emc",
        "دل ای‌ام‌سی",
        "United States",
        86,
        "https://www.dell.com/en-us/dt/storage/",
    ),
    brand("HP", "hp", "اچ‌پی", "United States", 95, "https://www.hp.com/"),
    brand("HPE", "hpe", "اچ‌پی‌ای", "United States", 92, "https://www.hpe.com/"),
    brand("Lenovo", "lenovo", "لنوو", "China", 95, "https://www.lenovo.com/"),
    brand("ASUS", "asus", "ایسوس", "Taiwan", 94, "https://www.asus.com/"),
    brand("Acer", "acer", "ایسر", "Taiwan", 85, "https://www.acer.com/"),
    brand("MSI", "msi", "ام‌اس‌آی", "Taiwan", 90, "https://www.msi.com/"),
    brand(
        "Gigabyte", "gigabyte", "گیگابایت", "Taiwan", 92, "https://www.gigabyte.com/"
    ),
    brand("ASRock", "asrock", "ازراک", "Taiwan", 88, "https://www.asrock.com/"),
    brand(
        "Supermicro",
        "supermicro",
        "سوپرمیکرو",
        "United States",
        88,
        "https://www.supermicro.com/",
    ),
    brand("Fujitsu", "fujitsu", "فوجیتسو", "Japan", 70, "https://www.fujitsu.com/"),
    brand("Huawei", "huawei", "هواوی", "China", 82, "https://www.huawei.com/"),
    brand("IBM", "ibm", "آی‌بی‌ام", "United States", 75, "https://www.ibm.com/"),
    brand("Oracle", "oracle", "اوراکل", "United States", 68, "https://www.oracle.com/"),
    # Memory and storage
    brand(
        "Samsung",
        "samsung",
        "سامسونگ",
        "South Korea",
        98,
        "https://www.samsung.com/semiconductor/",
    ),
    brand(
        "SK hynix",
        "sk-hynix",
        "اس‌کی هاینیکس",
        "South Korea",
        82,
        "https://www.skhynix.com/",
    ),
    brand(
        "Micron", "micron", "مایکرون", "United States", 86, "https://www.micron.com/"
    ),
    brand(
        "Crucial", "crucial", "کروشیال", "United States", 91, "https://www.crucial.com/"
    ),
    brand(
        "Kingston",
        "kingston",
        "کینگستون",
        "United States",
        95,
        "https://www.kingston.com/",
    ),
    brand(
        "Corsair", "corsair", "کورسیر", "United States", 94, "https://www.corsair.com/"
    ),
    brand("G.Skill", "g-skill", "جی‌اسکیل", "Taiwan", 90, "https://www.gskill.com/"),
    brand(
        "TeamGroup",
        "teamgroup",
        "تیم‌گروپ",
        "Taiwan",
        84,
        "https://www.teamgroupinc.com/",
    ),
    brand("ADATA", "adata", "ای‌دیتا", "Taiwan", 87, "https://www.adata.com/"),
    brand("XPG", "xpg", "ایکس‌پی‌جی", "Taiwan", 82, "https://www.xpg.com/"),
    brand(
        "Western Digital",
        "western-digital",
        "وسترن دیجیتال",
        "United States",
        97,
        "https://www.westerndigital.com/",
    ),
    brand(
        "SanDisk", "sandisk", "سن‌دیسک", "United States", 91, "https://www.sandisk.com/"
    ),
    brand(
        "Seagate", "seagate", "سیگیت", "United States", 97, "https://www.seagate.com/"
    ),
    brand("Toshiba", "toshiba", "توشیبا", "Japan", 86, "https://www.global.toshiba/"),
    brand("Kioxia", "kioxia", "کیوکسیا", "Japan", 85, "https://www.kioxia.com/"),
    brand(
        "Solidigm",
        "solidigm",
        "سالیدایم",
        "United States",
        78,
        "https://www.solidigm.com/",
    ),
    brand("Lexar", "lexar", "لکسر", "United States", 81, "https://www.lexar.com/"),
    brand("PNY", "pny", "پی‌ان‌وای", "United States", 80, "https://www.pny.com/"),
    brand(
        "Transcend",
        "transcend",
        "ترنسند",
        "Taiwan",
        80,
        "https://www.transcend-info.com/",
    ),
    brand(
        "Silicon Power",
        "silicon-power",
        "سیلیکون پاور",
        "Taiwan",
        78,
        "https://www.silicon-power.com/",
    ),
    brand(
        "Patriot",
        "patriot",
        "پاتریوت",
        "United States",
        77,
        "https://www.patriotmemory.com/",
    ),
    brand("Apacer", "apacer", "اپیسر", "Taiwan", 73, "https://www.apacer.com/"),
    brand("Netac", "netac", "نتک", "China", 68, "https://www.netac.com/"),
    brand("Sabrent", "sabrent", "سابرنت", "United States", 78, "https://sabrent.com/"),
    brand("Plextor", "plextor", "پلکستور", "Japan", 66),
    # Cases, power and cooling
    brand("NZXT", "nzxt", "ان‌زد‌ایکس‌تی", "United States", 88, "https://nzxt.com/"),
    brand(
        "Cooler Master",
        "cooler-master",
        "کولر مستر",
        "Taiwan",
        92,
        "https://www.coolermaster.com/",
    ),
    brand(
        "Thermaltake",
        "thermaltake",
        "ترمالتیک",
        "Taiwan",
        88,
        "https://www.thermaltake.com/",
    ),
    brand("Lian Li", "lian-li", "لیان‌لی", "Taiwan", 88, "https://lian-li.com/"),
    brand(
        "Fractal Design",
        "fractal-design",
        "فرکتال دیزاین",
        "Sweden",
        85,
        "https://www.fractal-design.com/",
    ),
    brand(
        "be quiet!", "be-quiet", "بی‌کوایت", "Germany", 86, "https://www.bequiet.com/"
    ),
    brand("Seasonic", "seasonic", "سی‌سونیک", "Taiwan", 92, "https://seasonic.com/"),
    brand("EVGA", "evga", "ای‌وی‌جی‌ای", "United States", 80, "https://www.evga.com/"),
    brand("FSP", "fsp", "اف‌اس‌پی", "Taiwan", 83, "https://www.fsp-group.com/"),
    brand(
        "SilverStone",
        "silverstone",
        "سیلوراستون",
        "Taiwan",
        82,
        "https://www.silverstonetek.com/",
    ),
    brand("DeepCool", "deepcool", "دیپ‌کول", "China", 89, "https://www.deepcool.com/"),
    brand("Noctua", "noctua", "نوکتوا", "Austria", 91, "https://noctua.at/"),
    brand("ARCTIC", "arctic", "آرکتیک", "Germany", 86, "https://www.arctic.de/"),
    brand("Antec", "antec", "انتک", "United States", 82, "https://www.antec.com/"),
    brand("Phanteks", "phanteks", "فنتکس", "Netherlands", 84, "https://phanteks.com/"),
    brand("Enermax", "enermax", "انرمکس", "Taiwan", 74, "https://www.enermax.com/"),
    # Networking and security
    brand("Cisco", "cisco", "سیسکو", "United States", 98, "https://www.cisco.com/"),
    brand(
        "Juniper Networks",
        "juniper",
        "جونیپر",
        "United States",
        90,
        "https://www.juniper.net/",
    ),
    brand(
        "Arista Networks",
        "arista",
        "آریستا",
        "United States",
        88,
        "https://www.arista.com/",
    ),
    brand(
        "Aruba", "aruba", "آروبا", "United States", 91, "https://www.arubanetworks.com/"
    ),
    brand(
        "Ubiquiti", "ubiquiti", "یوبیکیوتی", "United States", 93, "https://www.ui.com/"
    ),
    brand("MikroTik", "mikrotik", "میکروتیک", "Latvia", 95, "https://mikrotik.com/"),
    brand("TP-Link", "tp-link", "تی‌پی‌لینک", "China", 95, "https://www.tp-link.com/"),
    brand("D-Link", "d-link", "دی‌لینک", "Taiwan", 87, "https://www.dlink.com/"),
    brand(
        "NETGEAR", "netgear", "نت‌گیر", "United States", 88, "https://www.netgear.com/"
    ),
    brand("Tenda", "tenda", "تندا", "China", 78, "https://www.tendacn.com/"),
    brand("Zyxel", "zyxel", "زایکسل", "Taiwan", 84, "https://www.zyxel.com/"),
    brand(
        "Fortinet",
        "fortinet",
        "فورتی‌نت",
        "United States",
        96,
        "https://www.fortinet.com/",
    ),
    brand(
        "Palo Alto Networks",
        "palo-alto-networks",
        "پالو آلتو نتورکس",
        "United States",
        94,
        "https://www.paloaltonetworks.com/",
    ),
    brand("Sophos", "sophos", "سوفوس", "United Kingdom", 87, "https://www.sophos.com/"),
    brand(
        "Check Point",
        "check-point",
        "چک‌پوینت",
        "Israel",
        91,
        "https://www.checkpoint.com/",
    ),
    brand(
        "WatchGuard",
        "watchguard",
        "واچ‌گارد",
        "United States",
        82,
        "https://www.watchguard.com/",
    ),
    brand(
        "SonicWall",
        "sonicwall",
        "سونیک‌وال",
        "United States",
        84,
        "https://www.sonicwall.com/",
    ),
    brand(
        "Ruckus Networks",
        "ruckus",
        "راکوس",
        "United States",
        86,
        "https://www.ruckusnetworks.com/",
    ),
    brand(
        "Cambium Networks",
        "cambium",
        "کمبیوم",
        "United States",
        80,
        "https://www.cambiumnetworks.com/",
    ),
    brand(
        "Extreme Networks",
        "extreme-networks",
        "اکستریم نتورکس",
        "United States",
        84,
        "https://www.extremenetworks.com/",
    ),
    brand("Brocade", "brocade", "بروکید", "United States", 79),
    brand(
        "Mellanox",
        "mellanox",
        "ملانوکس",
        "Israel",
        88,
        "https://www.nvidia.com/en-us/networking/",
    ),
    brand(
        "Linksys", "linksys", "لینک‌سیس", "United States", 82, "https://www.linksys.com/"
    ),
    # NAS, SAN and data protection
    brand(
        "Synology", "synology", "سینولوژی", "Taiwan", 95, "https://www.synology.com/"
    ),
    brand("QNAP", "qnap", "کیونپ", "Taiwan", 93, "https://www.qnap.com/"),
    brand("NetApp", "netapp", "نت‌اپ", "United States", 91, "https://www.netapp.com/"),
    brand(
        "Pure Storage",
        "pure-storage",
        "پیور استوریج",
        "United States",
        86,
        "https://www.purestorage.com/",
    ),
    brand(
        "Hitachi Vantara",
        "hitachi-vantara",
        "هیتاچی ونتارا",
        "United States",
        84,
        "https://www.hitachivantara.com/",
    ),
    brand(
        "Infortrend",
        "infortrend",
        "اینفورترند",
        "Taiwan",
        76,
        "https://www.infortrend.com/",
    ),
    brand(
        "Promise Technology",
        "promise",
        "پرومیس",
        "United States",
        75,
        "https://www.promise.com/",
    ),
    brand("ASUSTOR", "asustor", "ازاستور", "Taiwan", 82, "https://www.asustor.com/"),
    brand(
        "TerraMaster",
        "terramaster",
        "ترامستر",
        "China",
        78,
        "https://www.terra-master.com/",
    ),
    brand(
        "Broadcom",
        "broadcom",
        "برادکام",
        "United States",
        89,
        "https://www.broadcom.com/",
    ),
    brand(
        "Quantum", "quantum", "کوانتوم", "United States", 76, "https://www.quantum.com/"
    ),
    # Power and data-center infrastructure
    brand("APC", "apc", "ای‌پی‌سی", "United States", 95, "https://www.apc.com/"),
    brand("Eaton", "eaton", "ایتون", "Ireland", 91, "https://www.eaton.com/"),
    brand("Vertiv", "vertiv", "ورتیو", "United States", 90, "https://www.vertiv.com/"),
    brand("Legrand", "legrand", "لگراند", "France", 87, "https://www.legrand.com/"),
    brand(
        "CyberPower",
        "cyberpower",
        "سایبرپاور",
        "United States",
        86,
        "https://www.cyberpowersystems.com/",
    ),
    brand(
        "Delta Electronics",
        "delta-electronics",
        "دلتا الکترونیکس",
        "Taiwan",
        85,
        "https://www.deltaww.com/",
    ),
    brand(
        "Schneider Electric",
        "schneider-electric",
        "اشنایدر الکتریک",
        "France",
        91,
        "https://www.se.com/",
    ),
    brand("Rittal", "rittal", "ریتال", "Germany", 84, "https://www.rittal.com/"),
    # Displays, printing and peripherals
    brand(
        "Logitech", "logitech", "لاجیتک", "Switzerland", 96, "https://www.logitech.com/"
    ),
    brand("Razer", "razer", "ریزر", "United States", 91, "https://www.razer.com/"),
    brand(
        "SteelSeries",
        "steelseries",
        "استیل‌سریز",
        "Denmark",
        88,
        "https://steelseries.com/",
    ),
    brand("HyperX", "hyperx", "هایپرایکس", "United States", 89, "https://hyperx.com/"),
    brand("BenQ", "benq", "بنکیو", "Taiwan", 89, "https://www.benq.com/"),
    brand("LG", "lg", "ال‌جی", "South Korea", 93, "https://www.lg.com/"),
    brand(
        "ViewSonic",
        "viewsonic",
        "ویوسونیک",
        "United States",
        86,
        "https://www.viewsonic.com/",
    ),
    brand("AOC", "aoc", "ای‌اوسی", "Taiwan", 86, "https://aoc.com/"),
    brand(
        "Philips", "philips", "فیلیپس", "Netherlands", 84, "https://www.philips.com/"
    ),
    brand("Epson", "epson", "اپسون", "Japan", 92, "https://www.epson.com/"),
    brand("Canon", "canon", "کانن", "Japan", 92, "https://www.canon.com/"),
    brand("Brother", "brother", "برادر", "Japan", 88, "https://www.brother.com/"),
    brand("Xerox", "xerox", "زیراکس", "United States", 85, "https://www.xerox.com/"),
    brand("Kyocera", "kyocera", "کیوسرا", "Japan", 83, "https://global.kyocera.com/"),
    brand(
        "Zebra Technologies",
        "zebra",
        "زبرا",
        "United States",
        84,
        "https://www.zebra.com/",
    ),
    brand("Wacom", "wacom", "وکوم", "Japan", 87, "https://www.wacom.com/"),
    brand("Elgato", "elgato", "الگاتو", "Germany", 85, "https://www.elgato.com/"),
)
