"""Representative products spanning recent hardware generations.

Prices are deterministic development-only values, not current market prices.
The seed service keeps every product in draft and invisible in the marketplace.
"""


def product(
    sku,
    name,
    slug,
    brand,
    category,
    sample_price,
    *,
    series_name=None,
    series_slug=None,
    year=None,
    generation="",
    model_number="",
    tags="",
    **fields,
):
    return {
        "sku": sku,
        "name": name,
        "slug": slug,
        "brand": brand,
        "category": category,
        "sample_price": sample_price,
        "series_name": series_name or name,
        "series_slug": series_slug or slug,
        "year": year,
        "generation": generation,
        "model_number": model_number,
        "tags": tags,
        "fields": fields,
    }


PRODUCTS = (
    # Desktop processors: recent Intel and AMD platform generations
    product(
        "SMP-CPU-I9-12900K",
        "Intel Core i9-12900K",
        "intel-core-i9-12900k",
        "intel",
        "home-desktop-cpu",
        280_000_000,
        year=2021,
        generation="12th Gen",
        processor="Intel Core i9-12900K",
        processor_cores=16,
        processor_threads=24,
        processor_speed="3.2 GHz",
        tags="cpu,intel,lga1700",
    ),
    product(
        "SMP-CPU-I9-13900K",
        "Intel Core i9-13900K",
        "intel-core-i9-13900k",
        "intel",
        "home-desktop-cpu",
        360_000_000,
        year=2022,
        generation="13th Gen",
        processor="Intel Core i9-13900K",
        processor_cores=24,
        processor_threads=32,
        processor_speed="3.0 GHz",
        tags="cpu,intel,lga1700",
    ),
    product(
        "SMP-CPU-I9-14900K",
        "Intel Core i9-14900K",
        "intel-core-i9-14900k",
        "intel",
        "home-desktop-cpu",
        430_000_000,
        year=2023,
        generation="14th Gen",
        processor="Intel Core i9-14900K",
        processor_cores=24,
        processor_threads=32,
        processor_speed="3.2 GHz",
        tags="cpu,intel,lga1700",
    ),
    product(
        "SMP-CPU-U9-285K",
        "Intel Core Ultra 9 285K",
        "intel-core-ultra-9-285k",
        "intel",
        "home-desktop-cpu",
        520_000_000,
        year=2024,
        generation="Core Ultra 200S",
        processor="Intel Core Ultra 9 285K",
        processor_cores=24,
        processor_threads=24,
        processor_speed="3.7 GHz",
        tags="cpu,intel,lga1851",
    ),
    product(
        "SMP-CPU-R9-5950X",
        "AMD Ryzen 9 5950X",
        "amd-ryzen-9-5950x",
        "amd",
        "home-desktop-cpu",
        250_000_000,
        year=2020,
        generation="Ryzen 5000",
        processor="AMD Ryzen 9 5950X",
        processor_cores=16,
        processor_threads=32,
        processor_speed="3.4 GHz",
        tags="cpu,amd,am4",
    ),
    product(
        "SMP-CPU-R9-7950X",
        "AMD Ryzen 9 7950X",
        "amd-ryzen-9-7950x",
        "amd",
        "home-desktop-cpu",
        390_000_000,
        year=2022,
        generation="Ryzen 7000",
        processor="AMD Ryzen 9 7950X",
        processor_cores=16,
        processor_threads=32,
        processor_speed="4.5 GHz",
        tags="cpu,amd,am5",
    ),
    product(
        "SMP-CPU-R9-9950X",
        "AMD Ryzen 9 9950X",
        "amd-ryzen-9-9950x",
        "amd",
        "home-desktop-cpu",
        480_000_000,
        year=2024,
        generation="Ryzen 9000",
        processor="AMD Ryzen 9 9950X",
        processor_cores=16,
        processor_threads=32,
        processor_speed="4.3 GHz",
        tags="cpu,amd,am5",
    ),
    # Server and workstation processors
    product(
        "SMP-CPU-EPYC-7763",
        "AMD EPYC 7763",
        "amd-epyc-7763",
        "amd",
        "dc-server-cpu",
        2_400_000_000,
        year=2021,
        generation="EPYC 7003",
        processor="AMD EPYC 7763",
        processor_cores=64,
        processor_threads=128,
        processor_speed="2.45 GHz",
        tags="cpu,server,epyc",
    ),
    product(
        "SMP-CPU-EPYC-9654",
        "AMD EPYC 9654",
        "amd-epyc-9654",
        "amd",
        "dc-server-cpu",
        4_700_000_000,
        year=2022,
        generation="EPYC 9004",
        processor="AMD EPYC 9654",
        processor_cores=96,
        processor_threads=192,
        processor_speed="2.4 GHz",
        tags="cpu,server,epyc",
    ),
    product(
        "SMP-CPU-EPYC-9965",
        "AMD EPYC 9965",
        "amd-epyc-9965",
        "amd",
        "dc-server-cpu",
        7_900_000_000,
        year=2024,
        generation="EPYC 9005",
        processor="AMD EPYC 9965",
        processor_cores=192,
        processor_threads=384,
        processor_speed="2.25 GHz",
        tags="cpu,server,epyc",
    ),
    product(
        "SMP-CPU-XEON-6338",
        "Intel Xeon Gold 6338",
        "intel-xeon-gold-6338",
        "intel",
        "dc-server-cpu",
        2_100_000_000,
        year=2021,
        generation="3rd Gen Xeon Scalable",
        processor="Intel Xeon Gold 6338",
        processor_cores=32,
        processor_threads=64,
        processor_speed="2.0 GHz",
        tags="cpu,server,xeon",
    ),
    product(
        "SMP-CPU-XEON-8480P",
        "Intel Xeon Platinum 8480+",
        "intel-xeon-platinum-8480-plus",
        "intel",
        "dc-server-cpu",
        5_900_000_000,
        year=2023,
        generation="4th Gen Xeon Scalable",
        processor="Intel Xeon Platinum 8480+",
        processor_cores=56,
        processor_threads=112,
        processor_speed="2.0 GHz",
        tags="cpu,server,xeon",
    ),
    product(
        "SMP-CPU-XEON-8592P",
        "Intel Xeon Platinum 8592+",
        "intel-xeon-platinum-8592-plus",
        "intel",
        "dc-server-cpu",
        7_200_000_000,
        year=2023,
        generation="5th Gen Xeon Scalable",
        processor="Intel Xeon Platinum 8592+",
        processor_cores=64,
        processor_threads=128,
        processor_speed="1.9 GHz",
        tags="cpu,server,xeon",
    ),
    product(
        "SMP-CPU-TRP-3995WX",
        "AMD Ryzen Threadripper PRO 3995WX",
        "amd-threadripper-pro-3995wx",
        "amd",
        "workstation-cpu",
        3_000_000_000,
        year=2020,
        generation="Threadripper PRO 3000 WX",
        processor="AMD Ryzen Threadripper PRO 3995WX",
        processor_cores=64,
        processor_threads=128,
        tags="cpu,workstation",
    ),
    product(
        "SMP-CPU-TRP-5995WX",
        "AMD Ryzen Threadripper PRO 5995WX",
        "amd-threadripper-pro-5995wx",
        "amd",
        "workstation-cpu",
        4_500_000_000,
        year=2022,
        generation="Threadripper PRO 5000 WX",
        processor="AMD Ryzen Threadripper PRO 5995WX",
        processor_cores=64,
        processor_threads=128,
        tags="cpu,workstation",
    ),
    product(
        "SMP-CPU-TRP-7995WX",
        "AMD Ryzen Threadripper PRO 7995WX",
        "amd-threadripper-pro-7995wx",
        "amd",
        "workstation-cpu",
        8_500_000_000,
        year=2023,
        generation="Threadripper PRO 7000 WX",
        processor="AMD Ryzen Threadripper PRO 7995WX",
        processor_cores=96,
        processor_threads=192,
        tags="cpu,workstation",
    ),
    # Consumer and professional graphics
    product(
        "SMP-GPU-RTX-3090",
        "NVIDIA GeForce RTX 3090",
        "nvidia-geforce-rtx-3090",
        "nvidia",
        "home-gaming-gpu",
        850_000_000,
        year=2020,
        generation="GeForce RTX 30",
        gpu="NVIDIA GeForce RTX 3090",
        gpu_memory="24GB GDDR6X",
        power_consumption="350W",
        tags="gpu,nvidia,geforce",
    ),
    product(
        "SMP-GPU-RTX-4090",
        "NVIDIA GeForce RTX 4090",
        "nvidia-geforce-rtx-4090",
        "nvidia",
        "home-gaming-gpu",
        1_650_000_000,
        year=2022,
        generation="GeForce RTX 40",
        gpu="NVIDIA GeForce RTX 4090",
        gpu_memory="24GB GDDR6X",
        power_consumption="450W",
        tags="gpu,nvidia,geforce",
    ),
    product(
        "SMP-GPU-RTX-5090",
        "NVIDIA GeForce RTX 5090",
        "nvidia-geforce-rtx-5090",
        "nvidia",
        "home-gaming-gpu",
        2_400_000_000,
        year=2025,
        generation="GeForce RTX 50",
        gpu="NVIDIA GeForce RTX 5090",
        gpu_memory="32GB GDDR7",
        power_consumption="575W",
        tags="gpu,nvidia,geforce",
    ),
    product(
        "SMP-GPU-RX-6950XT",
        "AMD Radeon RX 6950 XT",
        "amd-radeon-rx-6950-xt",
        "amd",
        "home-gaming-gpu",
        720_000_000,
        year=2022,
        generation="Radeon RX 6000",
        gpu="AMD Radeon RX 6950 XT",
        gpu_memory="16GB GDDR6",
        tags="gpu,amd,radeon",
    ),
    product(
        "SMP-GPU-RX-7900XTX",
        "AMD Radeon RX 7900 XTX",
        "amd-radeon-rx-7900-xtx",
        "amd",
        "home-gaming-gpu",
        1_050_000_000,
        year=2022,
        generation="Radeon RX 7000",
        gpu="AMD Radeon RX 7900 XTX",
        gpu_memory="24GB GDDR6",
        tags="gpu,amd,radeon",
    ),
    product(
        "SMP-GPU-RX-9070XT",
        "AMD Radeon RX 9070 XT",
        "amd-radeon-rx-9070-xt",
        "amd",
        "home-gaming-gpu",
        1_250_000_000,
        year=2025,
        generation="Radeon RX 9000",
        gpu="AMD Radeon RX 9070 XT",
        gpu_memory="16GB GDDR6",
        tags="gpu,amd,radeon",
    ),
    product(
        "SMP-GPU-A6000",
        "NVIDIA RTX A6000",
        "nvidia-rtx-a6000",
        "nvidia",
        "workstation-professional-gpu",
        2_900_000_000,
        year=2020,
        generation="Ampere",
        gpu="NVIDIA RTX A6000",
        gpu_memory="48GB GDDR6 ECC",
        power_consumption="300W",
        tags="gpu,workstation,nvidia",
    ),
    product(
        "SMP-GPU-6000-ADA",
        "NVIDIA RTX 6000 Ada Generation",
        "nvidia-rtx-6000-ada",
        "nvidia",
        "workstation-professional-gpu",
        4_900_000_000,
        year=2022,
        generation="Ada Lovelace",
        gpu="NVIDIA RTX 6000 Ada Generation",
        gpu_memory="48GB GDDR6 ECC",
        power_consumption="300W",
        tags="gpu,workstation,nvidia",
    ),
    product(
        "SMP-GPU-PRO6000-BW",
        "NVIDIA RTX PRO 6000 Blackwell",
        "nvidia-rtx-pro-6000-blackwell",
        "nvidia",
        "workstation-professional-gpu",
        8_900_000_000,
        year=2025,
        generation="Blackwell",
        gpu="NVIDIA RTX PRO 6000 Blackwell",
        gpu_memory="96GB GDDR7 ECC",
        power_consumption="600W",
        tags="gpu,workstation,ai,nvidia",
    ),
    # Motherboards and memory
    product(
        "SMP-MB-Z690-HERO",
        "ASUS ROG Maximus Z690 Hero",
        "asus-rog-maximus-z690-hero",
        "asus",
        "home-motherboard",
        420_000_000,
        year=2021,
        generation="Intel Z690",
        model_number="ROG MAXIMUS Z690 HERO",
        form_factor="ATX",
        tags="motherboard,intel,z690",
    ),
    product(
        "SMP-MB-Z790-HERO",
        "ASUS ROG Maximus Z790 Hero",
        "asus-rog-maximus-z790-hero",
        "asus",
        "home-motherboard",
        560_000_000,
        year=2022,
        generation="Intel Z790",
        model_number="ROG MAXIMUS Z790 HERO",
        form_factor="ATX",
        tags="motherboard,intel,z790",
    ),
    product(
        "SMP-MB-Z890-HERO",
        "ASUS ROG Maximus Z890 Hero",
        "asus-rog-maximus-z890-hero",
        "asus",
        "home-motherboard",
        690_000_000,
        year=2024,
        generation="Intel Z890",
        model_number="ROG MAXIMUS Z890 HERO",
        form_factor="ATX",
        tags="motherboard,intel,z890",
    ),
    product(
        "SMP-MB-X570-MASTER",
        "Gigabyte X570 AORUS Master",
        "gigabyte-x570-aorus-master",
        "gigabyte",
        "home-motherboard",
        350_000_000,
        year=2019,
        generation="AMD X570",
        form_factor="ATX",
        tags="motherboard,amd,x570",
    ),
    product(
        "SMP-MB-X670E-MASTER",
        "Gigabyte X670E AORUS Master",
        "gigabyte-x670e-aorus-master",
        "gigabyte",
        "home-motherboard",
        520_000_000,
        year=2022,
        generation="AMD X670E",
        form_factor="E-ATX",
        tags="motherboard,amd,x670e",
    ),
    product(
        "SMP-MB-X870E-MASTER",
        "Gigabyte X870E AORUS Master",
        "gigabyte-x870e-aorus-master",
        "gigabyte",
        "home-motherboard",
        650_000_000,
        year=2024,
        generation="AMD X870E",
        form_factor="E-ATX",
        tags="motherboard,amd,x870e",
    ),
    product(
        "SMP-RAM-VEN-32-D4",
        "Corsair Vengeance LPX 32GB DDR4",
        "corsair-vengeance-lpx-32gb-ddr4",
        "corsair",
        "home-desktop-memory",
        70_000_000,
        year=2020,
        generation="DDR4",
        ram="32GB DDR4",
        tags="ram,ddr4",
    ),
    product(
        "SMP-RAM-VEN-32-D5",
        "Corsair Vengeance 32GB DDR5",
        "corsair-vengeance-32gb-ddr5",
        "corsair",
        "home-desktop-memory",
        105_000_000,
        year=2022,
        generation="DDR5",
        ram="32GB DDR5",
        tags="ram,ddr5",
    ),
    product(
        "SMP-RAM-DOM-64-D5",
        "Corsair Dominator Titanium 64GB DDR5",
        "corsair-dominator-titanium-64gb-ddr5",
        "corsair",
        "home-desktop-memory",
        210_000_000,
        year=2023,
        generation="DDR5 Performance",
        ram="64GB DDR5",
        tags="ram,ddr5",
    ),
    product(
        "SMP-RAM-KSM32-32",
        "Kingston Server Premier 32GB DDR4 ECC",
        "kingston-server-premier-32gb-ddr4-ecc",
        "kingston",
        "dc-server-memory",
        110_000_000,
        year=2021,
        generation="DDR4 ECC",
        ram="32GB DDR4 ECC RDIMM",
        tags="ram,server,ecc",
    ),
    product(
        "SMP-RAM-KSM48-32",
        "Kingston Server Premier 32GB DDR5 ECC",
        "kingston-server-premier-32gb-ddr5-ecc",
        "kingston",
        "dc-server-memory",
        145_000_000,
        year=2023,
        generation="DDR5 ECC",
        ram="32GB DDR5 ECC RDIMM",
        tags="ram,server,ecc",
    ),
    product(
        "SMP-RAM-MTC40-64",
        "Micron 64GB DDR5 ECC RDIMM",
        "micron-64gb-ddr5-ecc-rdimm",
        "micron",
        "workstation-ecc-memory",
        270_000_000,
        year=2024,
        generation="DDR5 ECC",
        ram="64GB DDR5 ECC RDIMM",
        tags="ram,workstation,ecc",
    ),
    # Client and enterprise storage
    product(
        "SMP-SSD-870EVO-1T",
        "Samsung 870 EVO 1TB",
        "samsung-870-evo-1tb",
        "samsung",
        "home-sata-ssd",
        75_000_000,
        year=2021,
        generation="870 EVO",
        storage="1TB SATA SSD",
        storage_type="SATA SSD",
        total_storage="1TB",
        tags="ssd,sata",
    ),
    product(
        "SMP-SSD-MX500-1T",
        "Crucial MX500 1TB",
        "crucial-mx500-1tb",
        "crucial",
        "home-sata-ssd",
        68_000_000,
        year=2018,
        generation="MX500",
        storage="1TB SATA SSD",
        storage_type="SATA SSD",
        total_storage="1TB",
        tags="ssd,sata",
    ),
    product(
        "SMP-SSD-SA510-1T",
        "WD Blue SA510 1TB",
        "wd-blue-sa510-1tb",
        "western-digital",
        "home-sata-ssd",
        66_000_000,
        year=2022,
        generation="Blue SA510",
        storage="1TB SATA SSD",
        storage_type="SATA SSD",
        total_storage="1TB",
        tags="ssd,sata",
    ),
    product(
        "SMP-NVME-980PRO-1T",
        "Samsung 980 PRO 1TB",
        "samsung-980-pro-1tb",
        "samsung",
        "home-nvme-m2",
        95_000_000,
        year=2020,
        generation="980 PRO",
        storage="1TB M.2 NVMe",
        storage_type="NVMe PCIe 4.0",
        total_storage="1TB",
        form_factor="M.2 2280",
        tags="ssd,nvme,m2",
    ),
    product(
        "SMP-NVME-990PRO-2T",
        "Samsung 990 PRO 2TB",
        "samsung-990-pro-2tb",
        "samsung",
        "home-nvme-m2",
        185_000_000,
        year=2022,
        generation="990 PRO",
        storage="2TB M.2 NVMe",
        storage_type="NVMe PCIe 4.0",
        total_storage="2TB",
        form_factor="M.2 2280",
        tags="ssd,nvme,m2",
    ),
    product(
        "SMP-NVME-9100PRO-2T",
        "Samsung 9100 PRO 2TB",
        "samsung-9100-pro-2tb",
        "samsung",
        "home-nvme-m2",
        290_000_000,
        year=2025,
        generation="9100 PRO",
        storage="2TB M.2 NVMe",
        storage_type="NVMe PCIe 5.0",
        total_storage="2TB",
        form_factor="M.2 2280",
        tags="ssd,nvme,m2",
    ),
    product(
        "SMP-HDD-EXOS-X18",
        "Seagate Exos X18 18TB",
        "seagate-exos-x18-18tb",
        "seagate",
        "dc-enterprise-hdd",
        310_000_000,
        year=2020,
        generation="Exos X18",
        storage="18TB Enterprise HDD",
        storage_type="SATA HDD",
        total_storage="18TB",
        form_factor="3.5 inch",
        tags="hdd,enterprise",
    ),
    product(
        "SMP-HDD-EXOS-X20",
        "Seagate Exos X20 20TB",
        "seagate-exos-x20-20tb",
        "seagate",
        "dc-enterprise-hdd",
        355_000_000,
        year=2021,
        generation="Exos X20",
        storage="20TB Enterprise HDD",
        storage_type="SATA HDD",
        total_storage="20TB",
        form_factor="3.5 inch",
        tags="hdd,enterprise",
    ),
    product(
        "SMP-HDD-EXOS-X24",
        "Seagate Exos X24 24TB",
        "seagate-exos-x24-24tb",
        "seagate",
        "dc-enterprise-hdd",
        470_000_000,
        year=2023,
        generation="Exos X24",
        storage="24TB Enterprise HDD",
        storage_type="SATA HDD",
        total_storage="24TB",
        form_factor="3.5 inch",
        tags="hdd,enterprise",
    ),
    product(
        "SMP-ENT-SSD-PM893",
        "Samsung PM893 3.84TB",
        "samsung-pm893-3-84tb",
        "samsung",
        "dc-enterprise-sata-sas-ssd",
        580_000_000,
        year=2021,
        generation="PM893",
        storage="3.84TB Enterprise SATA SSD",
        storage_type="SATA SSD",
        total_storage="3.84TB",
        form_factor="2.5 inch",
        tags="ssd,enterprise,sata",
    ),
    product(
        "SMP-ENT-SSD-PM9A3",
        "Samsung PM9A3 3.84TB",
        "samsung-pm9a3-3-84tb",
        "samsung",
        "dc-enterprise-nvme",
        790_000_000,
        year=2021,
        generation="PM9A3",
        storage="3.84TB Enterprise NVMe SSD",
        storage_type="NVMe",
        total_storage="3.84TB",
        tags="ssd,enterprise,nvme",
    ),
    product(
        "SMP-ENT-SSD-D7P5520",
        "Solidigm D7-P5520 3.84TB",
        "solidigm-d7-p5520-3-84tb",
        "solidigm",
        "dc-enterprise-nvme",
        850_000_000,
        year=2022,
        generation="D7-P5520",
        storage="3.84TB Data Center NVMe SSD",
        storage_type="NVMe",
        total_storage="3.84TB",
        tags="ssd,datacenter,nvme",
    ),
    # Rack servers: three adjacent platform generations from each vendor
    product(
        "SMP-SRV-HPE-DL380-G10P",
        "HPE ProLiant DL380 Gen10 Plus",
        "hpe-proliant-dl380-gen10-plus",
        "hpe",
        "dc-rack-server",
        6_800_000_000,
        year=2021,
        generation="Gen10 Plus",
        series_name="ProLiant DL380",
        series_slug="proliant-dl380-gen10-plus",
        form_factor="2U",
        processor_count=2,
        ram_slots_total=32,
        network_ports=4,
        tags="server,rack,hpe",
    ),
    product(
        "SMP-SRV-HPE-DL380-G11",
        "HPE ProLiant DL380 Gen11",
        "hpe-proliant-dl380-gen11",
        "hpe",
        "dc-rack-server",
        9_500_000_000,
        year=2022,
        generation="Gen11",
        series_name="ProLiant DL380",
        series_slug="proliant-dl380-gen11",
        form_factor="2U",
        processor_count=2,
        ram_slots_total=32,
        network_ports=4,
        tags="server,rack,hpe",
    ),
    product(
        "SMP-SRV-HPE-DL380-G12",
        "HPE ProLiant Compute DL380 Gen12",
        "hpe-proliant-compute-dl380-gen12",
        "hpe",
        "dc-rack-server",
        13_500_000_000,
        year=2025,
        generation="Gen12",
        series_name="ProLiant Compute DL380",
        series_slug="proliant-compute-dl380-gen12",
        form_factor="2U",
        processor_count=2,
        network_ports=4,
        tags="server,rack,hpe",
    ),
    product(
        "SMP-SRV-DELL-R750",
        "Dell PowerEdge R750",
        "dell-poweredge-r750",
        "dell",
        "dc-rack-server",
        6_600_000_000,
        year=2021,
        generation="15G",
        series_name="PowerEdge R750",
        form_factor="2U",
        processor_count=2,
        ram_slots_total=32,
        network_ports=4,
        tags="server,rack,dell",
    ),
    product(
        "SMP-SRV-DELL-R760",
        "Dell PowerEdge R760",
        "dell-poweredge-r760",
        "dell",
        "dc-rack-server",
        9_800_000_000,
        year=2023,
        generation="16G",
        series_name="PowerEdge R760",
        form_factor="2U",
        processor_count=2,
        ram_slots_total=32,
        network_ports=4,
        tags="server,rack,dell",
    ),
    product(
        "SMP-SRV-DELL-R770",
        "Dell PowerEdge R770",
        "dell-poweredge-r770",
        "dell",
        "dc-rack-server",
        13_800_000_000,
        year=2025,
        generation="17G",
        series_name="PowerEdge R770",
        form_factor="2U",
        processor_count=2,
        network_ports=4,
        tags="server,rack,dell",
    ),
    product(
        "SMP-SRV-LEN-SR650-V2",
        "Lenovo ThinkSystem SR650 V2",
        "lenovo-thinksystem-sr650-v2",
        "lenovo",
        "dc-rack-server",
        6_500_000_000,
        year=2021,
        generation="V2",
        series_name="ThinkSystem SR650",
        form_factor="2U",
        processor_count=2,
        tags="server,rack,lenovo",
    ),
    product(
        "SMP-SRV-LEN-SR650-V3",
        "Lenovo ThinkSystem SR650 V3",
        "lenovo-thinksystem-sr650-v3",
        "lenovo",
        "dc-rack-server",
        9_600_000_000,
        year=2023,
        generation="V3",
        series_name="ThinkSystem SR650",
        form_factor="2U",
        processor_count=2,
        tags="server,rack,lenovo",
    ),
    product(
        "SMP-SRV-LEN-SR650-V4",
        "Lenovo ThinkSystem SR650 V4",
        "lenovo-thinksystem-sr650-v4",
        "lenovo",
        "dc-rack-server",
        13_600_000_000,
        year=2025,
        generation="V4",
        series_name="ThinkSystem SR650",
        form_factor="2U",
        processor_count=2,
        tags="server,rack,lenovo",
    ),
    # RAID, switching, routing and firewalls
    product(
        "SMP-RAID-9460-16I",
        "Broadcom MegaRAID 9460-16i",
        "broadcom-megaraid-9460-16i",
        "broadcom",
        "dc-raid-hba",
        520_000_000,
        year=2017,
        generation="SAS3",
        model_number="9460-16i",
        ports="16 internal SAS/SATA ports",
        tags="raid,hba,server",
    ),
    product(
        "SMP-RAID-9560-16I",
        "Broadcom MegaRAID 9560-16i",
        "broadcom-megaraid-9560-16i",
        "broadcom",
        "dc-raid-hba",
        710_000_000,
        year=2020,
        generation="Tri-Mode Gen4",
        model_number="9560-16i",
        tags="raid,hba,nvme",
    ),
    product(
        "SMP-RAID-9670W-16I",
        "Broadcom MegaRAID 9670W-16i",
        "broadcom-megaraid-9670w-16i",
        "broadcom",
        "dc-raid-hba",
        930_000_000,
        year=2023,
        generation="Tri-Mode Gen4.1",
        model_number="9670W-16i",
        tags="raid,hba,nvme",
    ),
    product(
        "SMP-SW-C9200L-24P",
        "Cisco Catalyst C9200L-24P-4G",
        "cisco-catalyst-c9200l-24p-4g",
        "cisco",
        "office-access-switch",
        1_250_000_000,
        year=2019,
        generation="Catalyst 9200L",
        model_number="C9200L-24P-4G",
        network_ports=24,
        form_factor="1U",
        tags="switch,cisco,poe",
    ),
    product(
        "SMP-SW-C9300-24T",
        "Cisco Catalyst C9300-24T",
        "cisco-catalyst-c9300-24t",
        "cisco",
        "dc-core-switch",
        2_800_000_000,
        year=2017,
        generation="Catalyst 9300",
        model_number="C9300-24T",
        network_ports=24,
        form_factor="1U",
        tags="switch,cisco",
    ),
    product(
        "SMP-SW-C9300X-24Y",
        "Cisco Catalyst C9300X-24Y",
        "cisco-catalyst-c9300x-24y",
        "cisco",
        "dc-core-switch",
        5_600_000_000,
        year=2021,
        generation="Catalyst 9300X",
        model_number="C9300X-24Y",
        network_ports=24,
        form_factor="1U",
        tags="switch,cisco",
    ),
    product(
        "SMP-RTR-CCR1009",
        "MikroTik CCR1009-7G-1C-1S+",
        "mikrotik-ccr1009-7g-1c-1s-plus",
        "mikrotik",
        "dc-enterprise-router",
        480_000_000,
        year=2014,
        generation="CCR1009",
        model_number="CCR1009-7G-1C-1S+",
        network_ports=9,
        form_factor="1U",
        tags="router,mikrotik",
    ),
    product(
        "SMP-RTR-CCR2004",
        "MikroTik CCR2004-1G-12S+2XS",
        "mikrotik-ccr2004-1g-12s-2xs",
        "mikrotik",
        "dc-enterprise-router",
        720_000_000,
        year=2020,
        generation="CCR2004",
        model_number="CCR2004-1G-12S+2XS",
        network_ports=15,
        form_factor="1U",
        tags="router,mikrotik",
    ),
    product(
        "SMP-RTR-CCR2216",
        "MikroTik CCR2216-1G-12XS-2XQ",
        "mikrotik-ccr2216-1g-12xs-2xq",
        "mikrotik",
        "dc-enterprise-router",
        1_650_000_000,
        year=2022,
        generation="CCR2216",
        model_number="CCR2216-1G-12XS-2XQ",
        network_ports=15,
        form_factor="1U",
        tags="router,mikrotik",
    ),
    product(
        "SMP-FW-FG-60F",
        "Fortinet FortiGate 60F",
        "fortinet-fortigate-60f",
        "fortinet",
        "office-firewall",
        680_000_000,
        year=2019,
        generation="F Series",
        model_number="FG-60F",
        tags="firewall,utm,fortinet",
    ),
    product(
        "SMP-FW-FG-70F",
        "Fortinet FortiGate 70F",
        "fortinet-fortigate-70f",
        "fortinet",
        "office-firewall",
        920_000_000,
        year=2022,
        generation="F Series",
        model_number="FG-70F",
        tags="firewall,utm,fortinet",
    ),
    product(
        "SMP-FW-FG-90G",
        "Fortinet FortiGate 90G",
        "fortinet-fortigate-90g",
        "fortinet",
        "dc-firewall-utm",
        1_450_000_000,
        year=2023,
        generation="G Series",
        model_number="FG-90G",
        tags="firewall,utm,fortinet",
    ),
    # NAS and SAN appliances
    product(
        "SMP-NAS-DS920P",
        "Synology DiskStation DS920+",
        "synology-diskstation-ds920-plus",
        "synology",
        "home-nas",
        520_000_000,
        year=2020,
        generation="20 Series",
        model_number="DS920+",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,synology",
    ),
    product(
        "SMP-NAS-DS923P",
        "Synology DiskStation DS923+",
        "synology-diskstation-ds923-plus",
        "synology",
        "office-nas",
        690_000_000,
        year=2022,
        generation="23 Series",
        model_number="DS923+",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,synology",
    ),
    product(
        "SMP-NAS-DS925P",
        "Synology DiskStation DS925+",
        "synology-diskstation-ds925-plus",
        "synology",
        "office-nas",
        840_000_000,
        year=2025,
        generation="25 Series",
        model_number="DS925+",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,synology",
    ),
    product(
        "SMP-NAS-TS453D",
        "QNAP TS-453D",
        "qnap-ts-453d",
        "qnap",
        "home-nas",
        510_000_000,
        year=2020,
        generation="TS-x53D",
        model_number="TS-453D",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,qnap",
    ),
    product(
        "SMP-NAS-TS453E",
        "QNAP TS-453E",
        "qnap-ts-453e",
        "qnap",
        "office-nas",
        650_000_000,
        year=2022,
        generation="TS-x53E",
        model_number="TS-453E",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,qnap",
    ),
    product(
        "SMP-NAS-TS464",
        "QNAP TS-464",
        "qnap-ts-464",
        "qnap",
        "office-nas",
        790_000_000,
        year=2022,
        generation="TS-x64",
        model_number="TS-464",
        storage="4-bay diskless NAS",
        network_ports=2,
        tags="nas,qnap",
    ),
    product(
        "SMP-SAN-MSA2050",
        "HPE MSA 2050 SAN Storage",
        "hpe-msa-2050-san-storage",
        "hpe",
        "dc-san-array",
        7_500_000_000,
        year=2017,
        generation="MSA 2050",
        model_number="MSA 2050",
        form_factor="2U",
        tags="san,storage,hpe",
    ),
    product(
        "SMP-SAN-MSA2060",
        "HPE MSA 2060 Storage",
        "hpe-msa-2060-storage",
        "hpe",
        "dc-san-array",
        10_500_000_000,
        year=2020,
        generation="MSA Gen6",
        model_number="MSA 2060",
        form_factor="2U",
        tags="san,storage,hpe",
    ),
    product(
        "SMP-SAN-MSA2070",
        "HPE MSA 2070 Storage",
        "hpe-msa-2070-storage",
        "hpe",
        "dc-san-array",
        14_500_000_000,
        year=2025,
        generation="MSA Gen7",
        model_number="MSA 2070",
        form_factor="2U",
        tags="san,storage,hpe",
    ),
    # Business laptops, all-in-one computers and mobile workstations
    product(
        "SMP-LAP-EB840-G9",
        "HP EliteBook 840 G9",
        "hp-elitebook-840-g9",
        "hp",
        "office-business-laptop",
        780_000_000,
        year=2022,
        generation="G9",
        series_name="EliteBook 840",
        processor="Intel Core i7-1265U",
        ram="16GB DDR5",
        storage="512GB NVMe SSD",
        total_storage="512GB",
        form_factor="Laptop",
        tags="laptop,business,hp",
    ),
    product(
        "SMP-LAP-EB840-G10",
        "HP EliteBook 840 G10",
        "hp-elitebook-840-g10",
        "hp",
        "office-business-laptop",
        940_000_000,
        year=2023,
        generation="G10",
        series_name="EliteBook 840",
        processor="Intel Core i7-1365U",
        ram="16GB DDR5",
        storage="512GB NVMe SSD",
        total_storage="512GB",
        form_factor="Laptop",
        tags="laptop,business,hp",
    ),
    product(
        "SMP-LAP-EB840-G11",
        "HP EliteBook 840 G11",
        "hp-elitebook-840-g11",
        "hp",
        "office-business-laptop",
        1_150_000_000,
        year=2024,
        generation="G11",
        series_name="EliteBook 840",
        processor="Intel Core Ultra 7 155U",
        ram="32GB DDR5",
        storage="1TB NVMe SSD",
        total_storage="1TB",
        form_factor="Laptop",
        tags="laptop,business,hp",
    ),
    product(
        "SMP-LAP-X1C-G11",
        "Lenovo ThinkPad X1 Carbon Gen 11",
        "lenovo-thinkpad-x1-carbon-gen-11",
        "lenovo",
        "office-ultrabook",
        1_050_000_000,
        year=2023,
        generation="Gen 11",
        series_name="ThinkPad X1 Carbon",
        processor="Intel Core i7-1365U",
        ram="16GB",
        storage="512GB NVMe SSD",
        form_factor="Ultrabook",
        tags="laptop,business,lenovo",
    ),
    product(
        "SMP-LAP-X1C-G12",
        "Lenovo ThinkPad X1 Carbon Gen 12",
        "lenovo-thinkpad-x1-carbon-gen-12",
        "lenovo",
        "office-ultrabook",
        1_280_000_000,
        year=2024,
        generation="Gen 12",
        series_name="ThinkPad X1 Carbon",
        processor="Intel Core Ultra 7 155U",
        ram="32GB",
        storage="1TB NVMe SSD",
        form_factor="Ultrabook",
        tags="laptop,business,lenovo",
    ),
    product(
        "SMP-LAP-X1C-G13",
        "Lenovo ThinkPad X1 Carbon Gen 13 Aura Edition",
        "lenovo-thinkpad-x1-carbon-gen-13",
        "lenovo",
        "office-ultrabook",
        1_520_000_000,
        year=2024,
        generation="Gen 13",
        series_name="ThinkPad X1 Carbon",
        processor="Intel Core Ultra 7",
        ram="32GB",
        storage="1TB NVMe SSD",
        form_factor="Ultrabook",
        tags="laptop,business,lenovo",
    ),
    product(
        "SMP-AIO-IMAC-M1",
        "Apple iMac 24-inch M1",
        "apple-imac-24-m1",
        "apple",
        "office-all-in-one",
        1_100_000_000,
        year=2021,
        generation="M1",
        series_name="iMac 24-inch",
        processor="Apple M1",
        ram="8GB unified memory",
        storage="256GB SSD",
        form_factor="All-in-One",
        tags="aio,apple,imac",
    ),
    product(
        "SMP-AIO-IMAC-M3",
        "Apple iMac 24-inch M3",
        "apple-imac-24-m3",
        "apple",
        "office-all-in-one",
        1_450_000_000,
        year=2023,
        generation="M3",
        series_name="iMac 24-inch",
        processor="Apple M3",
        ram="8GB unified memory",
        storage="256GB SSD",
        form_factor="All-in-One",
        tags="aio,apple,imac",
    ),
    product(
        "SMP-AIO-IMAC-M4",
        "Apple iMac 24-inch M4",
        "apple-imac-24-m4",
        "apple",
        "office-all-in-one",
        1_750_000_000,
        year=2024,
        generation="M4",
        series_name="iMac 24-inch",
        processor="Apple M4",
        ram="16GB unified memory",
        storage="256GB SSD",
        form_factor="All-in-One",
        tags="aio,apple,imac",
    ),
    product(
        "SMP-WS-PREC-5570",
        "Dell Precision 5570 Mobile Workstation",
        "dell-precision-5570",
        "dell",
        "workstation-mobile",
        1_750_000_000,
        year=2022,
        generation="Precision 5000 2022",
        series_name="Precision 5570",
        form_factor="Mobile Workstation",
        tags="workstation,laptop,dell",
    ),
    product(
        "SMP-WS-PREC-5680",
        "Dell Precision 5680 Mobile Workstation",
        "dell-precision-5680",
        "dell",
        "workstation-mobile",
        2_250_000_000,
        year=2023,
        generation="Precision 5000 2023",
        series_name="Precision 5680",
        form_factor="Mobile Workstation",
        tags="workstation,laptop,dell",
    ),
    product(
        "SMP-WS-PREC-5690",
        "Dell Precision 5690 Mobile Workstation",
        "dell-precision-5690",
        "dell",
        "workstation-mobile",
        2_850_000_000,
        year=2024,
        generation="Precision 5000 2024",
        series_name="Precision 5690",
        form_factor="Mobile Workstation",
        tags="workstation,laptop,dell",
    ),
    # Cases, PSUs and CPU cooling
    product(
        "SMP-CASE-H510",
        "NZXT H510",
        "nzxt-h510",
        "nzxt",
        "home-pc-case",
        105_000_000,
        year=2019,
        generation="H510",
        form_factor="Mid Tower",
        tags="case,atx",
    ),
    product(
        "SMP-CASE-H5-FLOW",
        "NZXT H5 Flow",
        "nzxt-h5-flow",
        "nzxt",
        "home-pc-case",
        150_000_000,
        year=2022,
        generation="H5",
        form_factor="Mid Tower",
        tags="case,atx",
    ),
    product(
        "SMP-CASE-H7-FLOW-24",
        "NZXT H7 Flow 2024",
        "nzxt-h7-flow-2024",
        "nzxt",
        "home-pc-case",
        230_000_000,
        year=2024,
        generation="H7 2024",
        form_factor="Mid Tower",
        tags="case,atx",
    ),
    product(
        "SMP-PSU-FOCUS-GX750",
        "Seasonic Focus GX-750",
        "seasonic-focus-gx-750",
        "seasonic",
        "home-pc-psu",
        145_000_000,
        year=2020,
        generation="Focus GX",
        power_supply="750W 80 Plus Gold",
        power_consumption="750W",
        tags="psu,power",
    ),
    product(
        "SMP-PSU-VERTEX-GX1000",
        "Seasonic Vertex GX-1000",
        "seasonic-vertex-gx-1000",
        "seasonic",
        "home-pc-psu",
        245_000_000,
        year=2023,
        generation="Vertex GX",
        power_supply="1000W 80 Plus Gold ATX 3.0",
        power_consumption="1000W",
        tags="psu,power",
    ),
    product(
        "SMP-PSU-PRIME-TX1300",
        "Seasonic Prime TX-1300",
        "seasonic-prime-tx-1300",
        "seasonic",
        "home-pc-psu",
        390_000_000,
        year=2024,
        generation="Prime TX",
        power_supply="1300W 80 Plus Titanium",
        power_consumption="1300W",
        tags="psu,power",
    ),
    product(
        "SMP-COOL-NHD15",
        "Noctua NH-D15",
        "noctua-nh-d15",
        "noctua",
        "home-air-cooling",
        135_000_000,
        year=2014,
        generation="NH-D15",
        tags="cooling,air,cpu",
    ),
    product(
        "SMP-COOL-NHD15S",
        "Noctua NH-D15S",
        "noctua-nh-d15s",
        "noctua",
        "home-air-cooling",
        145_000_000,
        year=2015,
        generation="NH-D15S",
        tags="cooling,air,cpu",
    ),
    product(
        "SMP-COOL-NHD15-G2",
        "Noctua NH-D15 G2",
        "noctua-nh-d15-g2",
        "noctua",
        "home-air-cooling",
        220_000_000,
        year=2024,
        generation="G2",
        tags="cooling,air,cpu",
    ),
    product(
        "SMP-AIO-LS720",
        "DeepCool LS720",
        "deepcool-ls720",
        "deepcool",
        "home-liquid-cooling",
        160_000_000,
        year=2022,
        generation="LS",
        tags="cooling,liquid,360mm",
    ),
    product(
        "SMP-AIO-LT720",
        "DeepCool LT720",
        "deepcool-lt720",
        "deepcool",
        "home-liquid-cooling",
        185_000_000,
        year=2022,
        generation="LT",
        tags="cooling,liquid,360mm",
    ),
    product(
        "SMP-AIO-MYSTIQUE360",
        "DeepCool MYSTIQUE 360",
        "deepcool-mystique-360",
        "deepcool",
        "home-liquid-cooling",
        275_000_000,
        year=2024,
        generation="MYSTIQUE",
        tags="cooling,liquid,360mm",
    ),
)
